spring:
  main:
    banner-mode: "off"

  mvc:
    throw-exception-if-no-handler-found: true
    problemdetails.enabled: true

  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

management:
  server:
    base-path: /management

server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never
  forward-headers-strategy: native
  servlet:
    encoding:
      force: true
    context-path: /

springdoc:
  swagger-ui.path: /swagger-ui.html

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{35} - %msg %n"
  level:
    ROOT: INFO
    ch.softwareplus.ai.ocr: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

